name: "Stream mqtt from Enphase Envoy"
description: "Converts Envoy Json to mqtt - V5 and v7 Envoy"
version: "1.0.18"
slug: "envoy_to_mqtt_json"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  MQTT_HOST: homeassistant.local
  MQTT_USER: mqtt.user
  MQTT_PASSWORD: mqtt.password
  MQTT_PORT: 1883
  MQTT_TOPIC: /envoy/json
  ENVOY_HOST: 192.168.1.72
  ENVOY_USER: enter.enphase.userid@email.com
  ENVOY_USER_PASS: enter.enphase.password
  USE_FREEDS: True
  DEBUG: False

schema:
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: password
  MQTT_PORT: int
  MQTT_TOPIC: str
  ENVOY_HOST: str
  ENVOY_USER: str
  ENVOY_USER_PASS: password
  USE_FREEDS: bool
  DEBUG: bool
